import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="bg-slate-800">
          <div className="max-w-5xl mx-auto px-10 py-3">
            <div className="bg-black rounded-md text-muted">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
